//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracion
    {
        public long Id { get; set; }
        public bool UsarLogin { get; set; }
        public bool UsarTicketera { get; set; }
        public bool MostrarDatos { get; set; }
    }
}
