//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleProducto
    {
        public long Id { get; set; }
        public long DetalleCajaId { get; set; }
        public string Descripcion { get; set; }
        public string Colegio { get; set; }
        public string Talle { get; set; }
        public decimal Cantidad { get; set; }
        public double Precio { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<long> ProductoId { get; set; }
    
        public virtual DetalleCaja DetalleCaja { get; set; }
    }
}
