//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCaja
    {
        public long Id { get; set; }
        public string Descripcion { get; set; }
        public decimal Total { get; set; }
        public long CajaId { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Caja Caja { get; set; }
    }
}
