//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido()
        {
            this.Producto_Pedido = new HashSet<Producto_Pedido>();
        }
    
        public long Id { get; set; }
        public decimal Total { get; set; }
        public decimal Adelanto { get; set; }
        public System.DateTime FechaPedido { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public Proceso Proceso { get; set; }
        public System.DateTime FechaEntrega { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto_Pedido> Producto_Pedido { get; set; }
    }
}
