//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    
    public enum Proceso : long
    {
        InicioPedido = 0,
        EsperandoRetiro = 1,
        PedidoTerminado = 2,
        CtaCte = 3,
        Guardado = 4,
        Retirado = 5
    }
}
