//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto_Dato
    {
        public long Id { get; set; }
        public EstadoPorPedido EstadoPorPedido { get; set; }
        public long Producto_PedidoId { get; set; }
        public bool EstaEliminado { get; set; }
    
        public virtual Producto_Pedido Producto_Pedido { get; set; }
    }
}
