//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto_Pedido
    {
        public long Id { get; set; }
        public long ProductoId { get; set; }
        public long PedidoId { get; set; }
        public EstadoPedido Estado { get; set; }
        public decimal Cantidad { get; set; }
        public string Talle { get; set; }
        public string Descripcion { get; set; }
        public long TalleId { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Pedido Pedido { get; set; }
        public virtual Talle TalleEntidad { get; set; }
    }
}
