//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Producto_Pedido = new HashSet<Producto_Pedido>();
            this.Producto_Venta = new HashSet<Producto_Venta>();
        }
    
        public long Id { get; set; }
        public string Descripcion { get; set; }
        public decimal Precio { get; set; }
        public bool EstaEliminado { get; set; }
        public string Extras { get; set; }
        public long TipoProductoId { get; set; }
        public long ColegioId { get; set; }
        public byte[] Foto { get; set; }
    
        public virtual TipoProducto TipoProducto { get; set; }
        public virtual Colegio Colegio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto_Pedido> Producto_Pedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto_Venta> Producto_Venta { get; set; }
    }
}
