//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TalleSegunProductoPrecio
    {
        public long Id { get; set; }
        public long PrecioSegunTalleId { get; set; }
        public long TalleId { get; set; }
    
        public virtual PrecioSegunTalle PrecioSegunTalle { get; set; }
        public virtual Talle Talle { get; set; }
    }
}
